### ISSUE TITLE
Variant Normalization (genomic location)

### ISSUE THREAD

**Issue by bwalsh** [ohsu-comp-bio/g2p-aggregator#1]
All knowledge bases should complete Feature genomic location.

**Comment by ahwagner** [comment]
This falls in line with my current work for the paper. You can assign it to me if you like. Would you prefer that I work on a branch as a project collaborator, or off of my own fork?

**Comment by bwalsh** [comment]
Thanks Alex.
A branch on the project makes the most sense, no? I'll add you as a collaborator.

**Comment by jgoecks** [comment]
Using the "per variant" CGI data file, I improved normalization of CGI here so that (a) COSMIC lookup is not needed and (b) it is much faster: https://github.com/ohsu-comp-bio/g2p-aggregator/commit/0f3c96ac95d9e543c0bbaa5f0ae5b3397ce0abe4

**Comment by jgoecks** [comment]
A first-pass on getting OncoKB variant-level information in is done: https://github.com/ohsu-comp-bio/g2p-aggregator/commit/7c71775c6c2e5c7ea50de4a2a89377fe75919e37

**Comment by jgoecks** [comment]
JAX is done as well: https://github.com/ohsu-comp-bio/g2p-aggregator/commit/ad73e01024ce647cf10614375947bceedf5d0bc0

A key question is whether we should represent ref/alt using the plus strand only or use strand-specific representation.

**Comment by bwalsh** [comment]
implemented in v0.3

**Comment by grmayfie** [comment]
Oncokb is not complete: only the clinical endpoint is being used, need to grab additional variant information from the biological endpoint. 

Related to [#19](https://github.com/ohsu-comp-bio/g2p-aggregator/issues/19) and [#30](https://github.com/ohsu-comp-bio/g2p-aggregator/issues/30).

**Comment by jgoecks** [comment]
If we're going to start hitting biological endpoints—which I assume to mean information about drivers/oncogenic annotations—then we're also missing stuff from CGI as well (https://www.cancergenomeinterpreter.org/mutations). We may be missing stuff from other sources as well.
