### ISSUE TITLE
normalize genes

### ISSUE THREAD

**Issue by ahwagner** [ohsu-comp-bio/g2p-aggregator#102]
We should incorporate gene normalization into our source harvesting.

Per discussion in #100, we should use the HGNC gene symbol file (ftp://ftp.ebi.ac.uk/pub/databases/genenames/new/json/non_alt_loci_set.json) to add Entrez Gene ID to each gene concept. We should also add Ensembl Gene ID. This file will already be in use for the improvements specified in #100.

**Comment by ahwagner** [comment]
@bwalsh see https://github.com/ahwagner/g2p-aggregator/blob/v0.10/notebooks/paper_analysis/viccdb.py#L54-L96 for how I am currently handling this in my analysis.

**Comment by bwalsh** [comment]
@ahwagner 
If agreeable,  I'll create a PR and refresh aws buckets later today with an additional field `gene_identifiers` that contains the symbol, entrez_id and ensembl_gene_id for each gene:

```
    .... 
    "genes": [
      "ALK"
    ],
    "gene_identifiers": [
      {
        "symbol": "ALK",
        "entrez_id": "238",
        "ensembl_gene_id": "ENSG00000171094"
      }
    ],
```

**Comment by ahwagner** [comment]
Sounds good. My only remaining concern about the implementation is minor, and documented [here](https://github.com/ohsu-comp-bio/g2p-aggregator/pull/100#issuecomment-380213745). Ideally these changes could be incorporated in the new PR.

**Comment by bwalsh** [comment]
Thanks.  I've added the following test
```
def test_ambiguous():
    """ "ABC1" can point to both "ABCA1" and "HEATR6", """
    genes = gene_enricher.get_genes('ABC1')
    assert genes == [
        {'symbol': u'ABCA1', 'entrez_id': u'19', 'ensembl_gene_id': u'ENSG00000165029'},
        {'symbol': u'HEATR6', 'entrez_id': u'63897', 'ensembl_gene_id': u'ENSG00000068097'}
    ]
```
