### ISSUE TITLE
enhance selection of multi-disease responses

### ISSUE THREAD

**Issue by ahwagner** [ohsu-comp-bio/g2p-aggregator#107]
Right now we select only the first of the normalized diseases provided by a harvested interpretation. We should improve this by:

- Identifying if the diseases have an ancestral relationship
  - if so, select the most specific
  - if not, warn and select nearest common ancestor

**Comment by bwalsh** [comment]
Agreed.  Currently the schema has phenotype as a single concept.  An enhancement would be to change it to phenotypes and store all conditions provided by the knowledge base
