### ISSUE TITLE
intuitive search

### ISSUE THREAD

**Issue by ahwagner** [ohsu-comp-bio/g2p-aggregator#125]
we need to restructure and/or better document the search functionality for users landing on the site. One potential option is to do de-emphasize (remove?) the free-text search bar, and preset a bunch of empty filters for the various components: drug, gene, variant, etc.

Another is to make clearer documentation and make it a clearer, more attractive starting point. My personal preference is for both.

**Comment by bwalsh** [comment]
@ahwagner Please review - I'll make a public instance available for review, hopefully by 2/4

## Proposed changes

![image](https://user-images.githubusercontent.com/47808/52097424-d8ce8c00-257f-11e9-90ad-2a0f269e3cb8.png)


## Refactored search

Default operator now `and` was `or`

### Current
 
 
![image](https://user-images.githubusercontent.com/47808/52097637-ad986c80-2580-11e9-9941-60806ae8a3cf.png)


### Proposed
![image](https://user-images.githubusercontent.com/47808/52097565-64e0b380-2580-11e9-81d6-f56afb9286fb.png)


## Refactored table

### Current

![image](https://user-images.githubusercontent.com/47808/52097691-ecc6bd80-2580-11e9-8182-fb25038a5631.png)

### Proposed

![image](https://user-images.githubusercontent.com/47808/52097829-6b235f80-2581-11e9-9ffc-0ebf60c32047.png)

**Comment by ahwagner** [comment]
@bwalsh proposed changes look good to me.

**Comment by ahwagner** [comment]
Some additional changes we should implement:
- [x] ensure source_url field URLs are presented as hyperlinks
![image](https://user-images.githubusercontent.com/811065/52595966-c290bd80-2e14-11e9-8490-6b3b8254da4a.png)
- [x] point the `help documentation` hyperlink in the intro paragraph to [docs.cancervariants.org](docs.cancervariants.org). 
- [x] add `brca` to the list of excluded sources on the paper filter
- [x] fix auto-sort on evidence level
- [ ] reduce filter drop-down menu options to preferentially sort or only display "short labels"

**Comment by ahwagner** [comment]
@bwalsh added some feedback from our call today to this issue.

**Comment by bwalsh** [comment]
@ahwagner 

I've updated the staging site at 35.165.177.191.
The items checked off above have been addressed.
A new bucket with the data is available at https://s3-us-west-2.amazonaws.com/g2p-0.12/index.html
The `drop-down menu options` cannot be shortened.  However, I have ensured that a filtered short lable eg evidence_lable does filter the results.

Let me know your thoughts




![image](https://user-images.githubusercontent.com/47808/53214795-d4d3de00-3602-11e9-93e6-03ec6b102a06.png)

**Comment by ahwagner** [comment]
These changes all look good. It appears that the "response" column broke, however; even records containing response_type data lack content in the relabeled column.

**Comment by ahwagner** [comment]
@bwalsh did you have a chance to look at comment above?

**Comment by bwalsh** [comment]
>It appears that the "response" column broke, however; even records
containing response_type data lack content in the relabeled column.

Yes, I resolved it.

**Comment by ahwagner** [comment]
Okay. I'm getting a weird error on my end–it looks like many of the columns are now broken, as is one of the interactive heatmaps.

![image](https://user-images.githubusercontent.com/811065/53529332-e2c9a900-3ab1-11e9-9195-331e6efa6173.png)

**Comment by bwalsh** [comment]
I'm currently reloading it ... my bad, should have told you first
-Brian Walsh

**Comment by ahwagner** [comment]
Fantastic. I'm going to bump this to production for co-author review, with the caveat that the Table 2 p. normalization (this issue) isn't yet completed.

**Comment by ahwagner** [comment]
Requests for JSON data from https://s3-us-west-2.amazonaws.com/g2p-0.12/index.html (e.g. https://s3-us-west-2.amazonaws.com/g2p-0.12/civic.json) return `Access Denied` errors. @bwalsh could you take a look at this?

**Comment by bwalsh** [comment]
@ahwagner  fixed.  thanks for the catch
