### ISSUE TITLE
nginx_g2p requires OHSU certificate

### ISSUE THREAD

**Issue by ahwagner** [ohsu-comp-bio/g2p-aggregator#14]
The current docker container for nginx (`nginx_g2p`) requires the use of an OHSU certificate (`/compbio-tls/compbio_ohsu_edu_cert.cer`). While this makes sense for the live version hosted by OHSU, it causes docker-compose to fail for off-site users.

@bwalsh, would you update the image for locale-agnostic instantiation? Or am I missing the way to adjust this for a local instance?

**Comment by bwalsh** [comment]
@ahwagner  I've updated the v0.3 branch. See [here](https://github.com/ohsu-comp-bio/g2p-aggregator/blob/v0.3/README.md#how-do-i-launch-the-database-bring-up-the-website-etc-).  Let me know if it works for you.

**Comment by bwalsh** [comment]
implemented in v0.3
