### ISSUE TITLE
What is the relationsihp between the VICC Meta-Knowledgebase and the GA4GH Variation Representation Specification?

### ISSUE THREAD

**Issue by mgurley** [ohsu-comp-bio/g2p-aggregator#147]
Can/are the variants that are normalized across the knowledgebases all mapped to the GA4GH Variation Representation Specification?  A VR Computed Identifier.

**Comment by ahwagner** [comment]
Hi @mgurley. Have you been getting my replies to your emails? Please check your spam, I am not sure why my messages are not getting through to you (from multiple accounts). Would be happy to meet up and discuss. Another mode of communication is Slack, you can join the [VICC Slack](https://ahw.pw/vicc-slack) and contact me there to set up a call.
