### ISSUE TITLE
Researcher support

### ISSUE THREAD

**Issue by bwalsh** [ohsu-comp-bio/g2p-aggregator#22]
Support researcher's activities to integrate g2p into:
* python notebooks
* pipelines

**Comment by bwalsh** [comment]
We gave integrated the on-campus instance into knight diagnostic labs fusion calling pipeline.   Basic functionality:

**Comment by jgoecks** [comment]
This is fantastic, I've got something similar for variant allele frequency as well. Let's plan to sync soon.
