### ISSUE TITLE
Publish pipeline & notebook integration cookbook

### ISSUE THREAD

**Issue by bwalsh** [ohsu-comp-bio/g2p-aggregator#23]

**Comment by grmayfie** [comment]
This is a task to make a wiki for outside people to understand how to use and integrate g2p into their own work.

**Comment by jgoecks** [comment]
I'm not sure where this goes in the priority list. We should discuss what we anticipate as the most compelling/useful interfaces to g2p. Some potential interfaces include Kibana, an API, a Python client, and "Oncotator-like annotations."

**Comment by grmayfie** [comment]
Closing, we have swagger API documentation.
