### ISSUE TITLE
Biomarker type normalization

### ISSUE THREAD

**Issue by bwalsh** [ohsu-comp-bio/g2p-aggregator#3]

**Comment by bwalsh** [comment]
### reference 
See https://api.molecularmatch.com/#aboutMutations

**Comment by jgoecks** [comment]
I added biomarker type for CGI here: https://github.com/ohsu-comp-bio/g2p-aggregator/commit/a42c2892f29ab324fd93212869ba4cfd93df582f

**Comment by bwalsh** [comment]
Dependency on #1  ;  Will require re-harvest and re-review once variant normalization complete for oncokb.

**Comment by bwalsh** [comment]
@bwalsh - please review PR

**Comment by bwalsh** [comment]
@mayfielg  can you review?  Perhaps biomarker_type might be extracted from jax & molecularmatch ?


biomarker_type | count_by_biomarker_type | source | count_by_source
-- | -- | -- | --
NA | 6507 | jax | 6507
snp | 3068 | civic | 1550
snp | 3068 | cgi | 1052
snp | 3068 | pmkb | 260
snp | 3068 | oncokb | 206
unspecified | 759 | civic | 357
unspecified | 759 | pmkb | 293
unspecified | 759 | oncokb | 85
unspecified | 759 | cgi | 24
transcript | 239 | civic | 239
fusion | 226 | civic | 149
fusion | 226 | cgi | 77
deletion | 200 | cgi | 108
deletion | 200 | oncokb | 49
deletion | 200 | civic | 29
deletion | 200 | pmkb | 14
amplification | 111 | cgi | 111
insertion | 82 | civic | 47
insertion | 82 | pmkb | 19
insertion | 82 | oncokb | 16
loss of function | 74 | civic | 74
exon | 66 | civic | 66
frameshift | 62 | civic | 47
frameshift | 62 | pmkb | 15
overexpression | 41 | cgi | 41
biallelic inactivation | 16 | cgi | 16
splice_region_variant | 14 | oncokb | 14
silent | 13 | civic | 13
stopgain | 13 | civic | 13
regulatory region variant | 8 | civic | 8
inframe variant | 6 | civic | 6
3 Prime UTR | 5 | civic | 5
loss of heterozygosity | 5 | civic | 5
indel | 4 | pmkb | 4
intron | 4 | civic | 4
feature_truncation | 3 | oncokb | 3
startloss | 3 | civic | 3
5 prime utr variant | 2 | civic | 2
polymorphic sequence variant | 2 | civic | 2
copy number change | 1 | civic | 1
microsatellite | 1 | civic | 1
short tandem repeat variation | 1 | civic | 1
splice donor variant | 1 | civic | 1
stop lost | 1 | civic | 1

**Comment by bwalsh** [comment]
I noticed molecular match now has biomarker_type.  I had to modify slightly in order to complete harvest.
Results are below.   Note that molecularmatch reports an array of mutation types.  For now, I've collapsed them into a CSV string.   We should consider if feature.biomarker_type should be feature.biomarker_types `[] an array`


biomarker_type | source.keyword: Descending | Count
-- | -- | --
NA | jax | 6507
snp | civic | 1550
snp | molecularmatch | 1053
snp | cgi | 1052
snp | pmkb | 260
snp | oncokb | 206
unspecified | civic | 357
unspecified | molecularmatch | 347
unspecified | pmkb | 293
unspecified | oncokb | 85
unspecified | cgi | 24
fusion | molecularmatch | 166
fusion | civic | 149
fusion | cgi | 77
transcript | civic | 239
transcript | molecularmatch | 101
deletion | cgi | 108
deletion | oncokb | 49
deletion | civic | 29
deletion | molecularmatch | 21
deletion | pmkb | 14
in frame,insertion | molecularmatch | 155
amplification | cgi | 111
loss of function | civic | 74
loss of function | molecularmatch | 36
insertion | civic | 47
insertion | pmkb | 19
insertion | oncokb | 16
insertion | molecularmatch | 2
exon | civic | 66
frameshift | civic | 47
frameshift | pmkb | 15
frameshift | molecularmatch | 3
silent,snp | molecularmatch | 51
fusion,snp | molecularmatch | 44
overexpression | cgi | 41
non sense | molecularmatch | 38
silent | molecularmatch | 22
silent | civic | 13
in frame,deletion | molecularmatch | 34
hotspot,snp | molecularmatch | 30
biallelic inactivation | cgi | 16
splice_region_variant | oncokb | 14
frame shift,deletion | molecularmatch | 13
stopgain | civic | 13
in frame,complex,deletion | molecularmatch | 12
gain of function,snp | molecularmatch | 10
in frame,complex,insertion | molecularmatch | 9
in frame,snp,insertion,hotspot | molecularmatch | 8
regulatory region variant | civic | 8
3 Prime UTR | civic | 5
3 Prime UTR | molecularmatch | 2
inframe variant | civic | 6
domain | molecularmatch | 5
frame shift,insertion | molecularmatch | 5
loss of heterozygosity | civic | 5
complex | molecularmatch | 4
frame shift | molecularmatch | 4
indel | pmkb | 4
intron | civic | 4
feature_truncation | oncokb | 3
frame shift,frameshift | molecularmatch | 3
startloss | civic | 3
stopgain,stop lost,non sense | molecularmatch | 3
5 prime utr variant | civic | 2
complex,frame shift | molecularmatch | 2
polymorphic sequence variant | civic | 2
polymorphic sequence variant,deletion | molecularmatch | 2
transcript,deletion | molecularmatch | 2
copy number change | civic | 1
exon,deletion | molecularmatch | 1
fusion,in frame,insertion | molecularmatch | 1
in frame | molecularmatch | 1
loss of function,snp | molecularmatch | 1
loss of function,stopgain,non sense | molecularmatch | 1
loss of function,stopgain,stop lost,non
  sense | molecularmatch | 1
microsatellite | civic | 1
microsatellite,snp | molecularmatch | 1
nonstop | molecularmatch | 1
short tandem repeat variation | civic | 1
splice donor variant | civic | 1
stop lost | civic | 1

**Comment by grmayfie** [comment]
I thought I accounted for the molecularmatch arrays to make singular results. Did you edit that or did something pass me by?

**Comment by grmayfie** [comment]
Jax has been updated, merged into v0.4. @bwalsh, how does that affect the counts you're seeing?
