### ISSUE TITLE
python notebook (overlaps and other metrics)

### ISSUE THREAD

**Issue by bwalsh** [ohsu-comp-bio/g2p-aggregator#33]
@ahwagner Hi.  During our last call, you showed a notebook that illustrated overlaps and other metrics?  Is it possible to share it? We can either incorporate it as-is or, perhaps we can adapt it into a test. Let me know your thoughts.

**Comment by ahwagner** [comment]
Hey @bwalsh. I had put this on another branch of the repo, you can find it here: https://github.com/ohsu-comp-bio/g2p-aggregator/blob/analysis/analysis/ES%20Store%20Analysis.ipynb

**Comment by bwalsh** [comment]
Thanks!

**Comment by jgoecks** [comment]
A couple quick comments before I forget:

- ElasticSearch DSL provides a high-level interface for interacting with ES that's much better than the base ES python client: https://elasticsearch-dsl.readthedocs.io/en/latest/
- UpSet would be a nice way to visualize these and other metrics for intersections among databases: https://github.com/ImSoErgodic/py-upset
