### ISSUE TITLE
Normalize Evidence Type

### ISSUE THREAD

**Issue by bwalsh** [ohsu-comp-bio/g2p-aggregator#4]
Use Civic? 
![image](https://cloud.githubusercontent.com/assets/47808/26115990/7968faf8-3a16-11e7-842a-3009cc07d7fa.png)

**Comment by grmayfie** [comment]
TODO: Need to push up the letter labels associated with this, as desgiend by the VIC group

**Comment by grmayfie** [comment]
Letter labels and corresponding numerical values have been added. 'evidence_label' for letters, corresponding to the VICC group's designations [here](https://docs.google.com/spreadsheets/d/1j9AKdv1k87iO8qH-ujnW3x4VusbGoXDjdb5apUqJsSI/edit#gid=1415903760). 'evidence_level' values are between 1 and 4, and correspond to A-D.

Merged into v0.4
