### ISSUE TITLE
Support IE

### ISSUE THREAD

**Issue by bwalsh** [ohsu-comp-bio/g2p-aggregator#44]

**Comment by grmayfie** [comment]
Recurring Issue: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.4.7/$rootScope/infdig?p0=10&p1=%5B%5D

According to the github kibana issues, this should be resolved in Kibana 5.5.2. Pushed up a branch moving to that version.

**Comment by grmayfie** [comment]
@bwalsh 

I think this is close-able too.
