### ISSUE TITLE
Disease normalization

### ISSUE THREAD

**Issue by bwalsh** [ohsu-comp-bio/g2p-aggregator#48]
@ahwagner 

Alex 

Hi.  I was hoping you might have some insight into an alias or lookup table we can use to get around this issue. 

Out of the 14,780 evidence items, we have 5,111 with no matched phenotype.
Out of those 5111 items, these 32 items have more than 10 entries each for a total of 4635.

Do you have any insight into what alias we might use for these items?

Thanks,

--

phenotype | Count
-- | --
Advanced Solid Tumor | 1571
Solid tumor | 634
Malignant neoplastic disease | 423
Neoplasm of respiratory tract | 417
Neoplasm of respiratory system | 407
Neoplasia | 153
Any cancer type | 142
Neoplasm of colon | 131
Neoplasm of rectum | 114
Neoplasm of digestive system | 105
Non-small cell lung | 66
Primary malignant neoplasm of   intrathoracic organs | 65
Gastrointestinal stromal | 60
Primary malignant neoplasm of lung | 46
Ovary | 29
T Lymphoblastic Leukemia/Lymphoma | 28
B Lymphoblastic Leukemia/Lymphoma | 21
Malignant tumour of soft tissue | 21
Chronic Myelomonocytic Leukemia | 20
Primary malignant neoplasm of bone marrow | 19
Malignant peripheral nerve sheat tumor | 18
Lung squamous cell | 17
Urothelial Carcinoma | 17
Neoplasm of breast | 16
Renal | 16
Diffuse Large B Cell Lymphoma | 13
Neoplasm of digestive tract | 12
Neoplasm of intra-abdominal organs | 12
Thyroid | 12
All Tumors | 10
Bladder BLCA | 10
MDS with Ring Sideroblasts | 10

**Comment by bwalsh** [comment]
@ahwagner @jgoecks  @mayfielg : FYI, please comment.

Before alias change:  5,111 phenotypes without DOID ontology id
After alias change:  196  phenotypes without DOID ontology id


## Alias table

name | alias
-- | --
ACC | Adrenocortical Carcinoma
Advanced Solid Tumor | Cancer
ALL | Acute Lymphoblastic Leukemia
All Solid Tumors | Cancer
All Tumors | Cancer
AML | Acute   Myeloid Leukemia
Any cancer   type | Cancer
APML | Acute   Promyelocytic Leukaemia
B   Lymphoblastic Leukemia/Lymphoma | B-cell adult acute lymphocytic   leukemia
BCC | Basal   cell carcinoma
BCL | B-Cell Lymphoma
Billiary tract | biliary   tract neoplasm
BLCA | Bladder Cancer
BOCA | Bone   Cancer
BRCA | Breast Cancer
BT | Biliary   Tract Cancer
BTCA | Biliary Tract Cancer
CCSK | Clear   Cell Sarcoma of the Kidney
CER | cervical cancer
CESC | Cervical   Squamous Cell Carcinoma
CH | Cholangiocarcinoma
CHOL | Cholangiocarcinoma
CLLE | Chronic Lymphocytic Leukemia
CMDI | Chronic   Myeloid Disorders
CNS | central nervous system cancer
COAD | Colon   Adenocarcinoma
COCA | Colorectal Cancer
COREAD | Colorectal   adenocarcinoma
Diffuse   Large B Cell Lymphoma | diffuse large B-cell lymphoma
DLBC | Lymphoid   Neoplasm Diffuse Large B-cell Lymphoma
EOPC | Early Onset Prostate Cancer
ESAD | Esophageal   Adenocarcinoma
ESCA | Esophageal Cancer
GACA | Gastric   Cancer
Gastrointestinal   stromal | Gastrointestinal stromal tumor
GBM | Glioblastoma   Multiforme
HNSC | Head and Neck Squamous Cell   Carcinoma
KICH | Kidney   Chromophobe
KIRC | Kidney Renal Clear Cell   Carcinoma
KIRP | Kidney   Renal Papillary Cell Carcinoma
L | Lung Cancer
LAML | Acute   Myeloid Leukemia
LGG | Brain Lower Grade Glioma
LIAD | Benign   Liver Tumour
LICA | Liver Cancer
LIHC | Liver   Hepatocellular Carcinoma
LIHM | Liver Cancer
LINC | Liver   Cancer
LIRI | Liver Cancer
LMS | Soft   tissue cancer
LUAD | Lung Adenocarcinoma
Lung squamous cell | lung   squamous cell carcinoma
LUSC | Lung Cancer
Malignant neoplastic disease | Cancer
Malignant   peripheral nerve sheat tumor | malignant peripheral nerve   sheath tumor
MALY | Malignant   Lymphoma
MELA | Skin Cancer
MESO | Mesothelioma
NBL | Neuroblastoma
Neoplasm of colon | Neoplasm   of the colon
Neoplasm of   colorectum | rectal neoplasm
Neoplasm of digestive system | gastrointestinal   system cancer
Neoplasm of   lung | lung adenocarcinoma
Neoplasm of rectum | rectum   cancer
Neoplasm of   respiratory system | respiratory system cancer
Neoplasm of respiratory tract | respiratory   system cancer
NKTL | Blood Cancer
Non-small cell lung | non-small   cell lung carcinoma
non-small   cell lung cancer | non-small cell lung carcinoma
ORCA | Oral   Cancer
OS | Osteosarcoma
OV | Ovarian   Cancer
Ovary | ovarian cancer
PAAD | Pancreatic   Cancer
PACA | Pancreatic Cancer
PRAD | Prostate   Cancer
READ | Rectum Adenocarcinoma
RECA | Renal   Cancer
RT | Rhabdoid Tumor
salivary duct carcinoma | salivary   gland carcinoma
SARC | Sarcoma
SKCA | Skin   Adenocarcinoma
SKCM | Skin Cutaneous Melanoma
Solid tumor | Cancer
Solid tumors | Cancer
STAD | Stomach   Adenocarcinoma
T   Lymphoblastic Leukemia/Lymphoma | acute T cell leukemia
TGCT | Testicular   Germ Cell Tumors
TH | Thyroid Cancer
THCA | Thyroid   Cancer
THYM | Thymoma
Thyroid | Thyroid   cancer
UC | bladder urachal urothelial   carcinoma
UCEC | Uterine   Corpus Endometrial Carcinoma
UCS | Uterine Carcinosarcoma
urothelial carcinoma | bladder   urachal urothelial carcinoma
UTCA | Uterine Cancer
UVM | Uveal   Melanoma
WT | Wilms Tumor

## Phenotypes without DOID

phenotype
--
Urothelial Carcinoma
Renal
MDS with Ring Sideroblasts
Desmoid Fibromatosis
Glial Neoplasm
T-cell Acute Lymphoblastic Leukemia
Head an neck
Histiocytic and Dendritic Cell Neoplasms
Langerhans Cell Histiocytosis
Bladder BLCA
Head an neck squamous
Myelodisplasic proliferative syndrome
Prostate adenocarcinoma PRAD
Soft Tissue Sarcoma
Epithelial Ovarian Cancer
Other Tumor Type
Thymic
Hepatic carcinoma
Lobular Carcinoma
Marginal Zone B Cell Lymphoma
Mesothelioma
Hematologic malignancies
Hepatocellular Fibrolamellar Carcinoma
Megakaryoblastic leukemia
Anaplastic Oligodendroglioma
CNS Cancer
Embryonal Tumor
Esophagogastric Cancer
Fibromatosis
Head an neck;Salivary glands
Intraductal Papillary Mucinous Neoplasm
Malignant astrocytoma
Myelodisplasic syndrome;Myelodisplasic   proliferative syndrome
Solid Tumor
Waldenström's Macroglobulinemia
mesothelioma
B cell lymphoma
Cervix
Cervix squamous cell
Chronic Eosinophilic Leukemia
Colorectal adenocarcinoma COREAD
Endometrial Hyperplasia
Epithelioid Hemangioendothelioma
Esophageal/Stomach Cancer, NOS
Hepatobiliary Cancer
Hepatocellular Mixed Fibrolamellar   Carcinoma
Histiocytic Disorder
Hyper eosinophilic advanced snydrome
Hyper eosinophilic advanced   snydrome;Eosinophilic chronic leukemia
Indication other than cancer
Male germ cell tumor
Nerve Sheath Tumor
Ovarian Granulosa Cell Tumor
PTEN Harmatoma Tumor Syndrome
Pediatric glioma
Pericytoma
Renal R
Sex Cord Stromal Tumor
Small Cell Carcinoma Of The Ovary   Hypercalcemic Type
Supratentorial Glioblastoma Multiforme
Urinary tract carcinoma
head and neck cancer
salivary duct carcinoma

**Comment by grmayfie** [comment]
Brian, which branch is in this work in so I can run it and look into it?

**Comment by bwalsh** [comment]
https://github.com/ohsu-comp-bio/g2p-aggregator/commit/7eae27e77f0047334ede2da4f275cc137c7898f1

**Comment by bwalsh** [comment]
closing based on call this AM.  re-open if necessary
