### ISSUE TITLE
Normalize Clinical Significance

### ISSUE THREAD

**Issue by bwalsh** [ohsu-comp-bio/g2p-aggregator#6]
As a researcher or informatician, in order to search or aggregate evidence that meets a given level, I need all evidence to be tagged with a consistent vocabulary.

Use civic?
![image](https://cloud.githubusercontent.com/assets/47808/26116083/bd098a16-3a16-11e7-978b-542a0a92307b.png)

**Comment by bwalsh** [comment]
I've created an extract of the values used by the different knowledge bases and the associated evidence counts here:
https://drive.google.com/open?id=1aU2TMU-XsT_xuIRG-R10Q-POBMaLR5XutOQ-TFOZaKM

**Comment by dms700** [comment]
I would recommend projecting this values onto AMP/ASCO/CAP guidelines:
http://jmd.amjpathol.org/cms/attachment/2076216919/2070244456/gr2_lrg.jpg
https://www.ncbi.nlm.nih.gov/pubmed/27993330

**Comment by jgoecks** [comment]
Also to consider are OncoKB's levels: http://oncokb.org/#/levels

**Comment by grmayfie** [comment]
Based on the photo in first comment, this is actually evidence direction, and should be completed barring any complaints. Thoughts?

**Comment by bwalsh** [comment]
I'll create a visualization showing existing work for review by VICC group.
