### ISSUE TITLE
Stable source / data release

### ISSUE THREAD

**Issue by ahwagner** [ohsu-comp-bio/g2p-aggregator#73]
Hey @bwalsh. On Tuesday we discussed having a static data silo that we could draw upon for the paper figures. Any progress on this front?

Also, we should identify a source branch that our analyses will be based upon--there may be some merging that needs to take place here (@jgoecks I'd like your input on this as well).

Let me know if I can help out at all with setting this up, so that we can move forward on generating the figures for the next paper call.

**Comment by bwalsh** [comment]
Hi @ahwagner 

Here are my updates:

>static data silo
* g2p-test.ddns.net - Test site, removes basic auth. Addresses #71
* a s3 bucket with static elastic snapshots exists [here](https://s3.console.aws.amazon.com/s3/buckets/g2p-test-snapshots/?region=us-east-1&tab=overview). 

> identify a source branch that our analyses
* v0.7 is the latest and greatest. 

>there may be some merging that needs to take place here
* I've merged the various notebooks into ./notebooks.   I re-tested them before checking in.

I'm currently working through [allele registry](http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/landing).  This would be the `final step` ;-o  Upon completion, I'll create static json files

**Comment by bwalsh** [comment]
# VERSION 0.7

This should be the 'frozen release'.   Anticipate any additional changes should be driven by paper analysis needs.

## location

_(I'll send email with bucket location)_

## contents

```
23604192 all.json
    6624 cgi.json
46192765 civic.json
   36912 jax.json
   10088 jax_trials.json
   61808 molecularmatch.json
23306360 molecularmatch_trials.json
   17104 oncokb.json
    3864 pmkb.json
     200 sage.json
```

Each file is contains evidence documents from the respective source.
`all.json` contains the aggregations of all sources.


source | count
-- | --
molecularmatch_trials | 199,069
jax | 5,754
brca | 5,717
oncokb | 4,048
civic | 3,497
molecularmatch | 2,079
cgi | 1,432
jax_trials | 1,173
pmkb | 609
sage | 69




evidence_label | count
-- | --
C | 167,453
B | 33,767
D | 16,703
A | 1,723


## structure


```
// An association between a phenotype('disease'), environment('drug')
// and genome(feature), harvested from a trusted knowledge base(source).
// For organization, the entrez name('genes') is included separately.
// For traceability, the document from the original source is included


message Evidence {
  string source = 1;
  repeated string genes = 2;

  // "ga4gh/sequence_annotations.proto"
  repeated google.protobuf.Struct features = 3;

  // "ga4gh/genotype_phenotype.proto"
  google.protobuf.Struct association = 4;

  // opaque source documents
  oneof opaque_source {
    google.protobuf.Struct cgi = 5;
    google.protobuf.Struct jax = 6;
    google.protobuf.Struct civic = 7;
    google.protobuf.Struct oncokb = 8;
    google.protobuf.Struct molecularmatch = 9;
    google.protobuf.Struct molecularmatch_trials = 10;
    google.protobuf.Struct jax_trials = 11;
    google.protobuf.Struct sage = 12;
  }  
}
```
<sub>Note: the feature and associations are based on [ga4gh.feature](https://github.com/ga4gh/ga4gh-schemas/blob/master/src/main/proto/ga4gh/sequence_annotations.proto#L30) and [ga4gh.FeaturePhenotypeAssociation](https://github.com/ga4gh/ga4gh-schemas/blob/master/src/main/proto/ga4gh/genotype_phenotype.proto#L124), but have evolved.  Future phases will create a PR to the appropriate GA4GH repository</sub>

**Comment by jgoecks** [comment]
I'm not sure if we should have this discussion here, but I continue to believe that we should exclude trials associations from our analysis for the manuscript. I suggest (a) figuring out what to do about trial associations and then (b) setting up a functional ES/Kibana with a snapshot of the data that we will use for and link to in the manuscript.

**Comment by bwalsh** [comment]
Sure, what ever makes sense.  As I recall, there was feedback from the last grant that we should include trials.

A quick glance shows that the trials sources are included automatically in the genie notebook.

![image](https://user-images.githubusercontent.com/47808/33510083-d35530a2-d6bc-11e7-9071-57d474e5fa4e.png)

**Comment by jgoecks** [comment]
I expect that new sources will just work with our analyses for the most part. Certainly clinical trials are valuable, but it may be a mistake to present clinical trials as sources in the paper. We may also want a separate database with only the knowledge base sources and not the trials data for the paper. @ahwagner This is probably worth discussing on the next paper call.

**Comment by ahwagner** [comment]
I agree with @jgoecks, as this broadens the scope of the paper too much. Yeah, we should definitely discuss on Tuesday.
