### ISSUE TITLE
oncokb clinical sample files for GENIE notebook

### ISSUE THREAD

**Issue by bwalsh** [ohsu-comp-bio/g2p-aggregator#76]
@mayfielg thanks. the code looks great.  trying to run GENIE notebook now.
where can I find the following files?  thanks.

![image](https://user-images.githubusercontent.com/47808/33980245-d9c9b990-e05c-11e7-999d-06b71a1567e5.png)

**Comment by bwalsh** [comment]
Are these the source of the notebook files?
http://www.cbioportal.org/study?id=msk_impact_2017#summary
However, there is no data_mutations_extended.txt  there?

**Comment by grmayfie** [comment]
Okay, yes, the reference from the OncoKB paper is http://www.cbioportal.org/study?id=msk_impact_2017#summary from the 'Download data' button.

@bwalsh

**Comment by bwalsh** [comment]
@mayfielg 
The notebook contains this line.
```
ONCOKB_MUTS = '../data/msk_impact_2017/data_mutations_extended.txt'
```
`data_mutations_extended.txt` is not in that down load

![image](https://user-images.githubusercontent.com/47808/34053869-4c3d5fec-e17d-11e7-982c-3bc96d9129a1.png)

The notebook is not reproducible:
For example, the checked in notebook has 
![image](https://user-images.githubusercontent.com/47808/34053943-935ef57a-e17d-11e7-96be-6fe1d39d9117.png)
When I try to run it:
![image](https://user-images.githubusercontent.com/47808/34053974-ae4ecbbc-e17d-11e7-85b4-7fa4f52c0832.png)

I'm concerned that figures downstream in the notebook are suggested for the paper.  They need to be reproducible.
![image](https://user-images.githubusercontent.com/47808/34054213-b7744ae0-e17e-11e7-8687-79b7b910e7fd.png)

**Comment by bwalsh** [comment]
I've created data/README.md - please add your updates

**Comment by grmayfie** [comment]
Okay, so it looks like msk-impact has had a data update, which is why the files are different/named differently. I've updated the notebook to reflect the new filenames. It does affect the output of the analysis, but as a rough overview, increases the amount of 'A' and 'B' level data. Updates will be lumped into the open [PR](https://github.com/ohsu-comp-bio/g2p-aggregator/pull/80).
