### ISSUE TITLE
brca exchange  "Pathogenicity_expert" filter

### ISSUE THREAD

**Issue by bwalsh** [ohsu-comp-bio/g2p-aggregator#79]
The possible values:

"Benign / Little Clinical Significance"
"Likely benign"
**"Not Yet Reviewed"**
"Pathogenic"
"Uncertain"

We currently filter out ["Not Yet Reviewed"](http://brcaexchange.org/variants?search=Not%20yet%20reviewed&orderBy=Pathogenicity_expert&order=ascending).  
We discussed removing that filter, can you confirm?

**Comment by jgoecks** [comment]
@bwalsh That is my opinion. Happy to have @ahwagner @malachig and others chime in as well.

**Comment by bwalsh** [comment]
@jgoecks 

Made the change - brca now has 17,584 items ( was 5,715 )
One note:  unreviewed items do not have a phenotype

```
+++ b/harvester/brca.py
@@ -22,10 +22,10 @@ def harvest(genes=None):
         else:
             page_num = page_num + 1
             for record in payload['data']:
-                if not record['Pathogenicity_expert'] == 'Not Yet Reviewed':
-                    gene = record['Gene_Symbol']
-                    gene_data = {'gene': gene, 'brca': record}
-                    yield gene_data
+                # if not record['Pathogenicity_expert'] == 'Not Yet Reviewed':
+                gene = record['Gene_Symbol']
+                gene_data = {'gene': gene, 'brca': record}
+                yield gene_data
```

**Comment by grmayfie** [comment]
@bwalsh I get slightly different results when I run this. 
source:brca: 17,546
source:brca AND _exists_:association.phenotype.description: 5,791

Whereas g2p-test shows a slightly higher overall result from BRCA and a slightly lower count with phenotype association. Is this just related to when the harvest was run do you think? 

Code looks good, just confused about number variation.

**Comment by bwalsh** [comment]
I'll check g2p-test tomorrow ( there were snafus uploading to it )

**Comment by ahwagner** [comment]
Per the group discussion today, we're reversing course on this and should exclude "Not Yet Reviewed" variants.

**Comment by bwalsh** [comment]
@ahwagner @mayfielg @jgoecks for your review...   addressed and deployed at https://g2p-test.ddns.net
