### ISSUE TITLE
Add selection for clinical trials sources to Kibana interface

### ISSUE THREAD

**Issue by ahwagner** [ohsu-comp-bio/g2p-aggregator#83]
For the paper we'll be focusing on our core variant interpretation/assertion sources, excluding clinical trial sources.

Consequently, we will need to develop an element in the Kibana interface that will allow users to toggle which databases the results will be sourced from.

**Comment by bwalsh** [comment]
@ahwagner @mayfielg @jgoecks for your review...   addressed and deployed at https://g2p-test.ddns.net

![image](https://user-images.githubusercontent.com/47808/35415427-6862423c-01da-11e8-8838-b5502592ab81.png)

addressed in https://github.com/ohsu-comp-bio/g2p-aggregator/commit/ff8ed246be556124fffea826a2cfc1ffc35737c9

FYI:

The `custom ui` feature, when released will have a 'no trials/all trials' toggle.

![image](https://user-images.githubusercontent.com/47808/35415514-be18370e-01da-11e8-9dc1-6e0ff22aa736.png)

**Comment by grmayfie** [comment]
👍
