### ISSUE TITLE
VICC Beacon and RESTful API

### ISSUE THREAD

**Issue by ahwagner** [ohsu-comp-bio/g2p-aggregator#85]
Our current VICC Beacon is non-compliant with the beacon swagger doc:

https://github.com/ga4gh/beacon-team/blob/develop/beacon.yaml

We'll need to perform the following changes:

- [ ] Collapse the 10 primary response objects into one response
- [ ] Aggregate and report the number of A/B/C/D interpretations in the `info` field
- [ ] Create a supplementary `search` endpoint that provides detailed responses from ElasticSearch index

Tagging as `review` per discussion with @jgoecks.

@bwalsh, would you provide a time estimate for the steps outlined here?

**Comment by grmayfie** [comment]
@ahwagner Can we close? Please close if appropriate.
