### ISSUE TITLE
Feature names inconsistent

### ISSUE THREAD

**Issue by ahwagner** [ohsu-comp-bio/g2p-aggregator#86]
All records from BRCA exchange have a list under the `feature_names` attribute, other sources have a string or None object here. The list is never longer than one item, so I propose we fix the harvester to assign only string or None objects to the `feature_names` attribute.

Omitting the `review` label because this is a straightforward, quick fix.

**Comment by bwalsh** [comment]
Can we combine this with https://github.com/ohsu-comp-bio/g2p-aggregator/issues/88 ?
( affects the same area of the code )

**Comment by bwalsh** [comment]
done https://github.com/ohsu-comp-bio/g2p-aggregator/commit/2fd2e8e7da618c349f16302b769ac9b622481d28
