### ISSUE TITLE
UI Search Results

### ISSUE THREAD

**Issue by ahwagner** [ohsu-comp-bio/g2p-aggregator#89]
Currently, searches of the type `Gene Variant` (e.g. `BRAF V600E`) do a global OR search between terms. Ideally, we could rename the `features.name` field to the mutation name (without the prepended gene symbol) and by default limit the search to a global AND condition.

Subtasks:
- [ ] remove prepended gene symbol in features.name, propogate changes to feature_names.keyword.
- [ ] change search behavior to AND by default

@bwalsh can you provide feedback on the feasibility of this?

**Comment by bwalsh** [comment]
>remove prepended gene symbol in features.name, propagate changes to feature_names.keyword.

A challenge in doing this is that the original source often includes just a string with gene the feature name or feature type or protein name,etc.  

Not pushing back on the idea, but may not be straightforward...

eg 
![image](https://user-images.githubusercontent.com/47808/36451107-c6f0ecd0-1644-11e8-9369-ae302271a5d5.png)

**Comment by bwalsh** [comment]
Can we merge this with https://github.com/ohsu-comp-bio/g2p-aggregator/issues/88

**Comment by bwalsh** [comment]
Both of these changes were problematic:
> remove prepended gene symbol in features.name
... location misses / fusions etc are are somewhat illegible if gene name removed. 
e.g.   "FGFR1-TACC1"  

> change search behavior to AND by default
... this is possible, but may artificially constrain full text searches.  suggest further testing.

**Comment by bwalsh** [comment]
Also,  re 'UI Search Results'  drug.toxicity has been remove from search index, since "liver" appears in many toxicity descriptions.

**Comment by grmayfie** [comment]
@ahwagner Can we close? Please close if appropriate.
