### ISSUE TITLE
pmkb interpretations are split

### ISSUE THREAD

**Issue by ahwagner** [ohsu-comp-bio/g2p-aggregator#98]
currently, we split interpretations from PMKB into 1 association per feature. The interpretation, however, applies to all of the features collectively. When harvesting PMKB, we should create associations with multiple features, instead of multiple associations (that are largely duplicated) with one feature each.

**Comment by ahwagner** [comment]
This is a low-priority task. It needs to be addressed before we publish, but I am already handling it (through an _ad hoc_ merging operation) in my analysis workbook.

**Comment by grmayfie** [comment]
It looks like the same thing that's now been resolved for civic is happening for other sources though.

oncokb example:
![image](https://user-images.githubusercontent.com/16827611/38525880-dbfcf012-3c08-11e8-9066-2f9ba19dd8cb.png)

**Comment by ahwagner** [comment]
Yes, this is the issue that was detected in #99.
